// Generated by CoffeeScript 1.7.1
(function() {
  var Firebase, add, firebase, get, increment_count, priority, q, sanitize, set, touch;

  Firebase = require('firebase');

  firebase = new Firebase(process.env.FIREBASE_ROOT);

  q = require('q');

  if (process.env.FIREBASE_KEY != null) {
    firebase.auth(process.env.FIREBASE_KEY, function() {
      return console.log('AUTHED');
    });
  }

  Array.prototype.last = function() {
    return this[this.length - 1];
  };

  sanitize = function(location) {
    return location.replace(/\.|#|\$|\[|\]/g, '');
  };

  get = function(location) {
    var deferred;
    deferred = q.defer();
    firebase.child(sanitize(location)).once('value', function(snapshot) {
      return deferred.resolve(snapshot.val());
    });
    return deferred.promise;
  };

  set = function(location, value) {
    var deferred;
    deferred = q.defer();
    firebase.child(sanitize(location)).setWithPriority(value, priority(location, value), function(err) {
      if (err != null) {
        return deferred.reject({
          context: 'readbase.set',
          error: err
        });
      } else {
        return deferred.resolve(true);
      }
    });
    return deferred.promise;
  };

  add = function(location, value) {
    var deferred;
    deferred = q.defer();
    get(location).then(function(val) {
      if (val != null) {
        return deferred.resolve(false);
      } else {
        return set(sanitize(location), value).then(function() {
          return increment_count(sanitize(location.split('/').slice(0, -1).join('/')));
        }).then(function() {
          return deferred.resolve(true);
        }).fail(function(err) {
          return deferred.reject({
            context: 'readbase.add',
            error: err
          });
        });
      }
    });
    return deferred.promise;
  };

  touch = function(location) {
    var deferred;
    deferred = q.defer();
    firebase.child(sanitize(location)).setPriority(priority(location), function(err) {
      if (err != null) {
        return deferred.reject(err);
      } else {
        return deferred.resolve(true);
      }
    });
    return deferred.promise;
  };

  increment_count = function(location) {
    var count, deferred;
    deferred = q.defer();
    count = location + '/count';
    firebase.child(sanitize(count)).once('value', function(snapshot) {
      var val;
      val = snapshot.val() || 0;
      return firebase.child(count).setWithPriority(++val, priority(location, val), function(err) {
        if (err != null) {
          return deferred.reject({
            context: 'increment_count',
            error: err
          });
        } else {
          return deferred.resolve();
        }
      });
    });
    return deferred.promise;
  };

  priority = function(location, value) {
    return Date.now();
  };

  module.exports = {
    get: get,
    set: set,
    add: add,
    priority: priority,
    increment_count: increment_count
  };

}).call(this);
